Add russian roulette feature
mindsers/sanpe-bot pull request #4
Opened 2021-04-17 23:09 UTC by Sata51

2021-04-17 23:18 UTC, Sata51 commented
I've also add a fix on the missing import on commands file

2021-04-19 15:52 UTC, arthurmadecprevost commented
Looks fine to me. Great job @Sata51.

2021-04-19 19:01 UTC, mindsers requested changes
Some random stuffs to fix. Still need to think about the bot forwarding btw...

2021-04-19 19:01 UTC, mindsers commented on package.json
> +		"@types/tmi.js": "^1.7.1",
Why do we need @types packages? This is not a TS project

2021-04-19 19:01 UTC, mindsers commented on src/bot/lib/bot.js
> +  async timeout(channel, username, reason, duration = 300) {
What is the difference between `timeout()` and `ban()` ; and why don't we use `timeout()` ?

2021-04-19 19:01 UTC, mindsers commented on src/bot/lib/modifiers/register-commands.js
> +      const result = await commands.get(commandName)({
Do we really need a separate variable here ?

2021-04-19 19:01 UTC, mindsers commented on src/bot/lib/modifiers/register-commands.js
> +        message: 'The commander should check my healph', // This typo is intensional. This is the sanpe-bot. sanpe looks like french for health
Love it ❤️

2021-04-19 19:01 UTC, mindsers commented on src/bot/commands/russian.js
> +const youths = ['padawan', 'noob', 'jedi', 'trekkie', 'elf']
This is great for a gaming channel. Should we find other analogies?

2021-04-19 19:01 UTC, mindsers commented on src/bot/lib/bot.js
> +  async timeout(channel, username, reason, duration = 300) {
Why not : 
```suggestion
  async timeout(username, duration = 300, reason = 'Because I can', channels = this.#channels) {
```

2021-04-19 19:01 UTC, mindsers commented on src/bot/lib/bot.js
> +  async ban(channel, username, reason) {
```suggestion
  async ban(username, reason = 'Ciao', channels = this.#channels) {
```

2021-04-19 19:01 UTC, mindsers commented on src/bot/lib/bot.js
> +  async unBan(channel, username) {
```suggestion
  async unBan(username, channels = this.#channels) {
```

2021-04-19 19:10 UTC, Sata51 commented on package.json
> +		"@types/tmi.js": "^1.7.1",
This make vscode autocomplete easier

2021-04-19 19:10 UTC, Sata51 commented on src/bot/lib/modifiers/register-commands.js
> +      const result = await commands.get(commandName)({
I think it looks easier, but we can do whatever you want my lord :D

2021-04-19 19:13 UTC, Sata51 commented on src/bot/lib/bot.js
> +  async timeout(channel, username, reason, duration = 300) {
ban and timeout are methods exposed by client. I just forward this implementation to keep it simple in futur implementation

2021-04-19 19:25 UTC, mindsers approved these changes
🚂

2021-04-19 19:25 UTC, merged

2021-04-23 08:34 UTC, mindsers commented
@all-contributors please add @Sata51 for code